apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcons-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falcons-api
  template:
    metadata:
      labels:
        app: falcons-api
    spec:
      containers:
      - name: falcons-api
        image: us.icr.io/falcons/app
        imagePullPolicy: Always
        ports:
        - containerPort: 5000